[ INFO ] The following arguments were obtained: ('--include', 'C2', '--debug', '--without_timestamps', '--loglevel', 'DEBUG', '--consoleloglevel', 'INFO', '--pabot', 'FULL')
[ DEBUG ] Started suite: 'Data 2'
[ INFO ] Starting to explore the dependencies...
[ DEBUG ] Investigating subsuite 'Data 2.suiteC'
[ DEBUG ] Requested test 'Data 2.suiteC.TestC2' because of --include option: 'C2'
[ DEBUG ] These are tests which user requested: ['Data 2.suiteC.TestC2']
[ INFO ] Starting relation chain checking...
[ INFO ] Checking relation chain for test 'Data 2.suiteC.TestC2'
[ DEBUG ] Dependency: 'Data 2.suiteC.TestC2' -> 'TestC1'
[ DEBUG ] Dependency: 'Data 2.suiteC.TestC1' -> 'TestC2'
[ INFO ] In test case 'Data 2.suiteC.TestC2' either the branches merge or it is a loop. Let's explore what we end up with if we start with this test.
[ INFO ] Starting in loop check mode.
[ DEBUG ] Dependency: 'Data 2.suiteC.TestC2' -> 'TestC1'
[ DEBUG ] Dependency: 'Data 2.suiteC.TestC1' -> 'TestC2'
[ ERROR ] Dependencies are cyclical! Test case 'Data 2.suiteC.TestC2' is already part of the relation chain: dict_values(['Data 2.suiteC.TestC2', 'Data 2.suiteC.TestC1']) Execution of tests cannot be started!
